### PR TITLE
[wip]: Add the functionality of join metadata and clades

### PR DESCRIPTION
**Pull request by j23414**
### Description of proposed changes

After some discussion with @joverlee521, moved `join-metadata-and-clades.py` from PR: https://github.com/nextstrain/ingest/pull/20 to this draft.

Some of the functionality may be replaced by `csvtk` but there are customized calculations in certain pathogen repositories. 

```
mpx/join-metadata-and-clades.py
        rsv/join-metadata-and-clades.py       3 lines different
        dengue/join-metadata-and-clades.py      IDENTICAL
        ncov/join-metadata-and-clades     114 lines different
```

This is a placeholder that the functionality of `join-metadata-and-clades` requires more discussion and thought. 

### Related issue(s)

Subset of scripts listed in https://github.com/nextstrain/ingest/issues/1

### Checklist

- [ ] Checks pass
- [ ] If adding a script, add an entry for it in the README.

### CODE REVIEW

**Comment by j23414** [comment]
We could combine the two files without performing complex calculations by using a combination of [csvtk rename](https://bioinf.shenwei.me/csvtk/usage/#rename) and [tsv-join](https://github.com/eBay/tsv-utils/blob/master/docs/tool_reference/tsv-join.md) as follows:

```shell
# Rename columns in the input.nextclade file
cat {input.nextclade} \
| csvtk -tl rename2 \
  -F \
  -f '*' \
  -p '(.+)' \
  -r '{{kv}}' \
  -k {input.nextclade_field_map} \
  > results/nextclade_renamed.tsv
  
# Join the renamed nextclade file with the input.metadata file
cat {input.metadata} \
 | tsv-join -H \
 --filter-file results/nextclade_renamed.tsv \
 --key-fields seqName \
 --data-fields accession \
 --append-fields `awk 'OFS=","{print $2}'` \
 --allow-duplicate-keys \
 --write-all -1 \
 > {output.metadata}
```

**Comment by joverlee521** [comment]
@j23414 Would you be up for replacing [join-metadata-and-clades](https://github.com/nextstrain/monkeypox/blob/942c1d00dd163ed837062828ad2869be2822a9ac/ingest/workflow/snakemake_rules/nextclade.smk#L65-L69) in monkeypox with your csvtk/tsv-join example? It would be nice to do a full test run there to see how the outputs compare.

**Comment by huddlej** [comment]
I found myself needing to implement [something similar in the flu_frequencies workflow](https://github.com/nextstrain/flu_frequencies/pull/25/commits/fec7d0ad80047aff5bfd2b43df938ba0a0790e82) and appreciated `csvtk join`'s option to specify different names for the join columns in the two inputs (e.g., `seqName` in Nextclade input and `strain` in metadata). I originally planned to use `tsv-join`, but I was frustrated by the need to rename columns to have a matching key column name in both inputs.

Independent from the tools you end up using here, you can drop the `cat` block from the code above such that this:

```
cat {input.nextclade} \
| csvtk -tl rename2 \
  -F \
  -f '*' \
  -p '(.+)' \
  -r '{{kv}}' \
  -k {input.nextclade_field_map} \
  > results/nextclade_renamed.tsv
```

becomes this:

```
csvtk -tl rename2 \
  -F \
  -f '*' \
  -p '(.+)' \
  -r '{{kv}}' \
  -k {input.nextclade_field_map} \
  {input.nextclade} > results/nextclade_renamed.tsv
```

**Comment by j23414** [comment]
Closed since this script is replaced with csvtk and tsv utils.

*  https://github.com/nextstrain/monkeypox/commit/d053086eab6c3aef5101bf3f1a25609398500a3e

**Pull request closed without merging**
